name: Create diff

on:
  workflow_dispatch:
    inputs:
      release-version:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Release version to create diff for'
        default: 'v12.0.0'
        # Input has to be provided for the workflow to run
        required: true

env:
  DIFF_RESULTS_FOLDER: ./diff-results
  RELEASE_VERSION: ${{ github.event.inputs.release-version }}
  
jobs:  
  check-release:
    outputs:
      is-creating-for-release-needed: ${{ steps.check123.outputs.folder-does-not-exist }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Evaluate lines
      id: evaluate-lines
      working-directory: ${{ env.DIFF_RESULTS_FOLDER }}
      run: echo ::set-output name=lines::$(ls -l | grep ${{ env.RELEASE_VERSION }} | wc -l)
  
    - name: testt
      id: check123
      run: |
        if [[ ${{ steps.evaluate-lines.outputs.lines }} == 0 ]];
        then
          echo "::set-output name=folder-does-not-exist::true"
        else
          echo "::set-output name=folder-does-not-exist::false"
        fi
        
    - name: Creation for release is needed
      if: ${{ steps.check123.outputs.folder-does-not-exist }} == true
      run: echo Creation for release is needed

    - name: Creation for release is NOT needed
      if: ${{ steps.check123.outputs.folder-does-not-exist }} == false
      run: echo Creation for release is NOT needed

  create-app:
    needs: check-release
    if: ${{ needs.check-release.outputs.is-creating-for-release-needed }} == true
    env:
      NODE_VERSION: 14
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Create app for release
      run: npx create-next-app@${{ env.RELEASE_VERSION }} --ts --use-npm ${{ env.RELEASE_VERSION }}
      working-directory: ${{ env.DIFF_RESULTS_FOLDER }}

    - name: Push new create-next-app to repo
      if:  steps.check-folder-for-release.outputs.folder-for-release-exists == '0'
      run:  |
        git config --global user.name 'Bennett Dams' 
        git config --global user.email 'bennettdams@users.noreply.github.com'
        git add -A
        git commit -m '[automated commit] Test'
        git push

    - name: Check folders for existence
      run: ls -l
      
    - name: See diff results folder
      run: ls -l ${{ env.DIFF_RESULTS_FOLDER }}
    
    
    
    
    
    
    
    
    
